exif:
    application:
      Mac: /usr/bin/exiftool 
      Windows: C:\Temp\python\iptcconvert\libs\exiftool.exe
    charset: utf-8
    shell: False
standards:
    - 
        name: exif
        pattern: '^\[EXIF\]\s*([\w\s\-/]*):\s(.*)'
    - 
        name: iptc
        pattern: '^\[IPTC\]\s*([\w\s\-/]*):\s(.*)'
    - 
        name: xmp
        pattern: '^\[XMP\]\s*([\w\s\-/]*):\s(.*)'
    - 
        name: pdf
        pattern: '^\[PDF\]\s*([\w\s\-/]*):\s(.*)'
iptc2pdf:
  Headline: Subject
  Keywords: Keywords
  Caption-Abstract: Title
  DateCreated: xmp:Event
  ProgramVersion: null
  OriginatingProgram: null
  ApplicationRecordVersion: null
  CopyrightNotice: xmp:Copyright
  Source: xmp:Source
  SpecialInstructions: xmp:Instructions
  By-line: xmp:Creator
  Credit: xmp:Credit
  
    
    